### ISSUE TITLE
json_encode results in JSON_ERROR_UTF8 because of uuid field

### ISSUE THREAD

**Issue by faustbrian** [spatie/laravel-binary-uuid#13]
Currently it is not possible to json serialize any model that uses this package because the uuid field is in binary format.

```
json_encode(\App\Announcement::first());

dd(json_last_error()); // Results in 5 which equals JSON_ERROR_UTF8
```

I am currently solving this issue by using `protected $hidden = ['uuid'];` and `protected $appends = ['id']` where ID is the method from here https://github.com/spatie/laravel-binary-uuid/pull/12

It might be worth considering to replace the uuid field data with the uuid_text attribute value for the array format to allow working with it without any extra hacks like I do right now.

**Comment by faustbrian** [comment]
This is what I currently use as a workaround for all my models.

```php
<?php

namespace App\Traits;

use Illuminate\Database\Eloquent\Model;

trait HasUuidPrimaryKey
{
    /**
     * Get the textual id of the entity.
     *
     * @return string
     */
    public function getIdAttribute()
    {
        return $this->uuid_text;
    }

    /**
     * Get the hidden attributes for the model.
     *
     * @return array
     */
    public function getHidden()
    {
        return ['uuid'] + $this->hidden;
    }

    /**
     * Get the primary key for the model.
     *
     * @return string
     */
    public function getKeyName()
    {
        return 'uuid';
    }

    /**
     * Get the value indicating whether the IDs are incrementing.
     *
     * @return bool
     */
    public function getIncrementing()
    {
        return false;
    }
}
```

**Comment by freekmurze** [comment]
@brendt didn't we take care of this while developing the package?

**Comment by brendt** [comment]
This packages takes care of part of this problem. Namely when a model is serialised in queues. 

I'll answer on the concrete solution in PR #12
