### ISSUE TITLE
Package breaks Laravel Notifications because of overwrites

### ISSUE THREAD

**Issue by faustbrian** [spatie/laravel-binary-uuid#19]
Laravels database notifications use `$table->uuid('id')->primary();` by default so using this package breaks them which results in `SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'id' at row 1`.

`$table->char('id', 36)->primary();` solves the issue but having to change the default migrations is kinda off-putting.

```php
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateNotificationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('notifications', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('type');
            $table->morphs('notifiable');
            $table->text('data');
            $table->timestamp('read_at')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('notifications');
    }
}
```

**Comment by brendt** [comment]
Any thoughts besides what already discussed in #14 how we could fix this problem?

@freekmurze do you have any input?

**Comment by freekmurze** [comment]
The easiest solution would be to add a little note in the readme with instructions on how to edit the default migration.

Let's do that first, maybe that is good enough for most.

**Comment by brendt** [comment]
I've added a little more explanation in the README: https://github.com/spatie/laravel-binary-uuid#a-note-on-the-uuid-blueprint-method

Sadly I don't see a better workaround for this, unless some changes are made in the core. These changes are in discussion over here: https://github.com/laravel/internals/issues/645
