### ISSUE TITLE
UUID is not properly formatted

### ISSUE THREAD

**Issue by elliotfehr** [spatie/laravel-binary-uuid#24]
The article linked in the readme describes how to format uuid v1 for mysql, however it does not appear that this library is correctly optimizing.  While storing the UUID as a binary is a massive improvement over storing it as a `CHAR`/`VARCHAR`, it is only part of the problem.

A standard UUID v1 will generate a very poor primary key as the first half of the UUID is based on time while the second half is based on MAC address. The UUID needs to be reordered going into the database in order to have an efficient binary tree.

For example:
- https://github.com/Weebly/laravel-mutate/blob/master/src/Mutators/UuidV1BinaryMutator.php#L29-L37
- https://github.com/Weebly/laravel-mutate/blob/master/src/Mutators/UuidV1BinaryMutator.php#L54-L61

**Comment by brendt** [comment]
That's what's happing by using `OrderedTimeCodec` set in https://github.com/spatie/laravel-binary-uuid/blob/master/src/UuidServiceProvider.php#L47 

Am I missing something?

**Comment by elliotfehr** [comment]
Ahh I was looking for where that was done!
