### ISSUE TITLE
Undefined property when declearing uuid method

### ISSUE THREAD

**Issue by driesvints** [spatie/laravel-binary-uuid#26]
Heya, I'm trying to defined the following method on a modal which uses this library's trait but I get the following exception. Any idea why this is happening? Can't seem to wrap my head around it.

```php
    public function uuid(): UuidInterface
    {
        return Uuid::fromString($this->uuid_text);
    }
```

```
ErrorException: Undefined property: App\Models\Subscription::$uuid in /Users/driesvints/Sites/laravelio/vendor/spatie/laravel-binary-uuid/src/HasBinaryUuid.php:81
```

Let me know if you want more info.

**Comment by freekmurze** [comment]
I guess that you have `protected $primaryKey = 'uuid';` on your model. Correct?

Does the underlying table have a column named `uuid`?

**Comment by driesvints** [comment]
> I guess that you have protected $primaryKey = 'uuid'; on your model. Correct?

No, I only applied the traits like it said in the docs :)

> Does the underlying table have a column named uuid?

Yep:

<img width="222" alt="screen shot 2017-12-10 at 10 26 49 pm" src="https://user-images.githubusercontent.com/594614/33809562-48de4136-ddf9-11e7-9084-f443e6a41803.png">

Thanks for helping!

**Comment by freekmurze** [comment]
> No, I only applied the traits like it said in the docs :)

Ah, I missed that this is being set by the package in the  `HasUuidPrimaryKey` trait.

Could you try these things in a tinker session:

```php
$subscription = Subscription::first();

$subscription->uuid; //should return the uuid

$keyName = $subscription->getKeyName() // should return 'uuid'

$subscription->$keyName // should return the uuid;
```

**Comment by driesvints** [comment]
Problem is that I can't create a record atm because of the fatal error. I tried manually entering a record in the db with a binary UUID from another app which I hope is ok. The output was the one you were expecting although `$subscription->uuid;` and `$subscription->$keyName;` gave me some weird results, probably because the UUID wasn't created through the app and it feels like it was still binary.

**Comment by driesvints** [comment]
Some more info about the columns:

<img width="625" alt="screen shot 2017-12-11 at 11 44 29 pm" src="https://user-images.githubusercontent.com/594614/33857750-41988a2e-decd-11e7-86a7-df0ff038cdaf.png">

**Comment by driesvints** [comment]
@freekmurze I updated the screenshot above. The one you got with the Github notification isn't correct.

**Comment by brendt** [comment]
@driesvints could you share the code of your migration and the model class?

Sidenote: 

> The output was the one you were expecting although $subscription->uuid; and $subscription->$keyName; gave me some weird results,

`$keyName` giving strange output is expected, as it returns the raw binary data. `->uuid_text` will return the textual output.

**Comment by driesvints** [comment]
@brendt sure. All of the code is in this PR: https://github.com/laravelio/portal/pull/320

**Comment by brendt** [comment]
@driesvints It's the name of the method causing the issue:

```php
public function uuid(): UuidInterface
{
    return Uuid::fromString($this->uuid_text);
}
```

If `uuid` is used as both a method name and a field name, I think Laravel will always prefer the method over the field, causing the error. I tested this with a local project and can reproduce the same error this way.

I you want to keep using the method, you could as well rename the primary field to eg. `uuid_binary` or just plain `id` if you're not using integer IDs. The idea of the package is that you shouldn't worry about the binary UUID, so you won't encounter that field in your codebase. The only place you'll need to set the name of the primary key is by implementing `public function getKeyName()` in your model, the default `HasUuidPrimaryKey` trait won't work anymore.

**Comment by brendt** [comment]
@driesvints Any more input on this one?

**Comment by driesvints** [comment]
Haven't found the time yet to look at it again, sorry. I'll try to get back to this as soon as I can.

**Comment by driesvints** [comment]
Heya, really sorry but I've decided to just go with regular UUID's instead and just implement a custom implementation. I never figured out how to solve this and it's the last thing holding me back from releasing a new feature. Hope someone finds the time to look into this. Good luck and thanks for all the help!

**Comment by brendt** [comment]
@driesvints thanks for letting us know. 

For future reference: there's a PR (https://github.com/spatie/laravel-binary-uuid/pull/35) addressing the issue of the field names, so it shouldn't be a problem anymore once that PR is merged.
