### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by georgeboot** [spatie/laravel-binary-uuid#27]
What is the reason for the dependency `"laravel/framework": "~5.5.22"`? I created a fork and replaced it with `"laravel/lumen-framework": "~5.5"` and it works successfully.

And reasons not to include Lumen support?

**Comment by freekmurze** [comment]
We specified Laravel 5.5.22 because in lower versions of the framework queuing a model with binary uuid will result in errors and tears.

Unfortunately v5.5.22 is not yet tagged on illuminate/queue. As soon as that tag is there, we'll revisit this issue.

**Comment by westphalen** [comment]
+1

**Comment by brendt** [comment]
@georgeboot I tagged a new version [1.1.3](https://github.com/spatie/laravel-binary-uuid/releases/tag/1.1.3) containing only the dependency on `laravel/queue`.
