### ISSUE TITLE
Incompatible with Laravel Horizon

### ISSUE THREAD

**Issue by francislavoie** [spatie/laravel-binary-uuid#28]
Laravel Horizon has a feature where it tries to tag a jobs intelligently if it sees that the object passed into the job is an Eloquent model. When they do this, they use [`$model->getKey()`](https://github.com/laravel/horizon/blob/1.0/src/Tags.php#L29). With binary UUIDs, `getKey()` returns a binary string, so things kinda explode in there when it tries to pass the string to Redis.

I'm not sure what other side effects overriding `getKey()` to instead pass the UUID as a string would have, but I think this needs to be fixed in some way or another.

Edit: Did a quick find in all files for `->getKey()`... Apparently it gets used all over the place to do `WHERE` SQL queries, so I don't think overriding it would do much good (without additional changes). I'm not sure where to go from here. I reported it on [laravel/horizon](https://github.com/laravel/horizon) to see what happens.

**Comment by brendt** [comment]
I think that as soon as we're able to define custom blueprint methods, we can also tackle this issue. The reason why is that this would mean a BC breaking change, so it's better to bundle them. And for that we're waiting om some changes in the Laravel core. That discussion can be found here: https://github.com/spatie/laravel-binary-uuid/issues/14

My proposal would be that we would not be relying on `getKey` anymore, but rather allow the binary ID to be a normal indexed field in the database which can be used to search upon. We would still provide the helper methods for casting and querying, but you would need to specify the field name as a property on every model. Internally you can than still use normal IDs (for eg. relations and Horizon stuff) which only benefits the case for performance.

**Comment by francislavoie** [comment]
Thanks for the answer. For now I have to manually set the tags on all my jobs as a workaround.

**Comment by tdondich** [comment]
@francislavoie , see my pending PR for laravel horizon at https://github.com/laravel/horizon/pull/405
