### ISSUE TITLE
"Malformed UTF-8 characters, possibly incorrectly encoded" with uuid relations

### ISSUE THREAD

**Issue by zJoul** [spatie/laravel-binary-uuid#30]
I have some hard times with uuid relations and json representation.

My `work` model has two foreign keys (`user_id` and `workstation_id`) in binary format.
My `user` model has a `hasMany` relationship with the `work` model.

My controller looks like :
```php
public function show($uuid)
{
    $user = User::withUuid($uuid)
        ->with('profile')
        ->with('works')
        ->first();

    if (! $user) {
        abort(404);
    }

    return compact('user');
}
```
It throw the error mentionned in the title.

But it works well with tinker :
```php
$user = User::withUuid('2094a25a-efde-11e7-8005-f156302fb27e')->with('profile')->with('works')->paginate(10)->first();
[!] Aliasing 'User' to 'App\User' for this Tinker session.
=> App\User {#795
     id: b"\x11çïÞ ”¢Z€\x05ñV0/²~",
     username: "amber.pagac",
     email: "calista20@example.com",
     firstname: "Kip",
     lastname: "Lindgren",
     group: "e",
     profile_id: 1,
     login_count: 0,
     created_at: "2018-01-02 16:58:16",
     updated_at: "2018-01-02 16:58:16",
     deleted_at: null,
     profile: App\Profile {#808
       id: 1,
       name: "neque",
       description: "Aut mollitia quis amet necessitatibus aliquid consequatur. Cum eum a voluptas incidunt iusto magnam quasi. Quia quis maiores sit ut omnis dolor. Quis doloremque aut totam unde hic sed sunt.",
       created_at: "2018-01-02 16:58:16",
       updated_at: "2018-01-02 16:58:16",
       deleted_at: null,
     },
     works: Illuminate\Database\Eloquent\Collection {#807
       all: [
         App\Work {#805
           id: b"\x11çðg‰EC*–…]`¯!\x11w",
           user_id: b"\x11çïÞ ”¢Z€\x05ñV0/²~",
           workstation_id: b"\x11çïÞ l\x15ˆ©'!¨ÅKÁ‹",
           started_at: "2017-12-12 10:24:41",
           ended_at: "2017-12-12 11:05:37",
           grade_id: 2,
         },
         App\Work {#802
           id: b"\x11þ­gë\DlØ╣ëª¡║:\x7F",
           user_id: b"\x11çïÞ ”¢Z€\x05ñV0/²~",
           workstation_id: b"\x11þ´Ì bsHèØsq─╣óî",
           started_at: "2017-12-13 12:46:31",
           ended_at: "2017-12-17 20:53:32",
           grade_id: 3,
         },
         App\Work {#801
           id: b"\x11çðg‰k³„³³Áâ\x07”˜ˆ",
           user_id: b"\x11çïÞ ”¢Z€\x05ñV0/²~",
           workstation_id: b"""
             \x11çïÞ mTR¢\n
             iF±ïQz
             """,
           started_at: "2017-12-16 03:18:59",
           ended_at: "2017-12-25 22:40:29",
           grade_id: 1,
         },
       ],
     },
   }
```
If I append the `toJson()` method on the tinker command line, it throw an error `Illuminate\Database\Eloquent\JsonEncodingException with message 'Error encoding model [App\User] with ID [��� ��Z��V0/�~] to JSON: Malformed UTF-8 characters, possibly incorrectly encoded'`.

If I append the `toArray()` method, only the work id is translated to a string.

I guess the problem comes from the json encoding of the `user_id` and `workstation_id` in the Work model.

I tried to use the [withUuid](https://github.com/spatie/laravel-binary-uuid#querying-relations) mentionned in the README, but I don't have a `work_id` in my `users` table.

Is there a way to encode the faulty uuid ?
 
Forget to mention, I work with PHP7.2 and Laravel 5.5

**Comment by brendt** [comment]
So it seems that the issue doesn't come from the `->with` call, as it works with tinker.

Is it possible that `return compact('user');` tries to return a JSON? This should be visible from the error trace.

If so, you can override the `->jsonSerialize` method in the model, to support the custom relations:

```php
public function jsonSerialize()
{
    return array_merge(parent::jsonSerialize(), ['user_id' => User::decodeUuid($this->user->id)]);
}
```

I'm afraid relations won't be automatically converted in our current implementation.

**Comment by zJoul** [comment]
You're right, `compact` return an array, and thus it's being displayed as JSON on the browser.

I tried to override the method without success.
I ended not displaying JSON, but I guess I could `$hidden` the `user_id` and the `workstation_id` in the `Work` Model.

**Comment by brendt** [comment]
@zJoul could you share your solution here before we close this issue?

**Comment by masterix21** [comment]
Hi dears,

i found the same error using Passport and uuid for user_id column.

Try yourself with:

```php
Schema::create('oauth_auth_codes', function (Blueprint $table) {
            $table->string('id', 100)->primary();
            $table->uuid('user_id');
            $table->integer('client_id');
            $table->text('scopes')->nullable();
            $table->boolean('revoked');
            $table->dateTime('expires_at')->nullable();
        });
```

and next generate a token from /oauth/token.

**Comment by zJoul** [comment]
@brendt Of course, I just call my view in my controller :
```php
return view('user.profile', compact('user'));
```

And if I need the id to be displayed, I just call
```php
{{ $work->workstation->uuid_text }}
```

Althought I do not know about JSON representation

**Comment by brendt** [comment]
I'm going to close this issue, and refer to https://github.com/spatie/laravel-binary-uuid/issues/14 for followup, we'll revisit the default `uuid` behaviour and serialisation of the binary fields for the next major version.

**Comment by andreidmour** [comment]
> Hi dears,
> 
> i found the same error using Passport and uuid for user_id column.
> 
> Try yourself with:
> 
> ```
> Schema::create('oauth_auth_codes', function (Blueprint $table) {
>             $table->string('id', 100)->primary();
>             $table->uuid('user_id');
>             $table->integer('client_id');
>             $table->text('scopes')->nullable();
>             $table->boolean('revoked');
>             $table->dateTime('expires_at')->nullable();
>         });
> ```
> 
> and next generate a token from /oauth/token.

Did you manage to find a solution for this problem?

**Comment by masterix21** [comment]
@andreidmour sorry, no. I have changed package, without binary conversion.

**Comment by ekpono** [comment]
i am using Uuid to for user. After submiting the form i get this error `"Error encoding model [Koboaccountant\Models\User] with ID [790c48b8-3eb5-5a31-ad77-333d642ef5b1] to JSON: Malformed UTF-8 characters, possibly incorrectly encoded ◀"`

**Comment by vpratfr** [comment]
What does your user class look like? 

Did you add the `$uuids` protected field?

Did you append uuid_text and hide uuid from json serialization?

**Comment by vpratfr** [comment]
May be a good idea to open your own issue. This one is closed.
