### ISSUE TITLE
Error when using with Implicit route model binding

### ISSUE THREAD

**Issue by DennisOng** [spatie/laravel-binary-uuid#32]
Getting the following error when using implicit route model binding:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uuid_text' in 'where clause' (SQL: select * from `projects` where `uuid_text` = e775e0aa-f407-11e7-8a11-080027a8df8b limit 1)

Seems like it's using `uuid_text` as defined in getRouteKeyName().

My current workaround is to add a middleware to encode the UUID before the route model binding kicks in, and change the routeKeyName to `uuid`, which seem to work. But would love to hear if there's any better solution.

Great package for a very common use-case anyhow, thanks!

**Comment by brendt** [comment]
Hey and thanks for reporting this issue!

This is kind of a difficult one to tackle, because if we're not overriding `getRouteKeyName`, you'll get binary encoded values in generated URLs if I'm not mistaken.

The encoding and decoding needs to happen somewhere, and I'm not a 100% sure where the best place for it should be. A middleware seems like the correct place, but you would still need to add it to your routes using UUIDs in URLs.

Do you see other solutions which might solve your case in a better way?

**Comment by DennisOng** [comment]
Hey Brendt, I'm not too familiar with the 'url generation' part that you mentioned, do you mean when doing something like 
`url("/posts/{$post->id}")`?

**Comment by brendt** [comment]
In that case you're manually generating URLs, but if you're using [route model binding](https://laravel.com/docs/5.5/routing#route-model-binding), Laravel will automagically resolve things for you. Without overriding `getRouteKeyName`, the binary ID will be used, which we don't want.

**Comment by slashequip** [comment]
I was just looking into this issue myself for my own project.

I was tempted to make a tweaked version of the `Illuminate\Routing\Middleware\SubstituteBindings` middleware & related classes which will can look up the model by the binary UUID - this would potentially cause issues with non-uuid models.

Alternatively and probably much easier would be to overwrite the `resolveRouteBinding` function from the `Model`class:

```
/**
 * Retrieve the model for a bound value.
 *
 * @param  mixed  $value
 * @return \Illuminate\Database\Eloquent\Model|null
 */
 public function resolveRouteBinding($value)
 {
     // return $this->where($this->getRouteKeyName(), $value)->first();
     return $this->where($this->getRouteKeyName(), self::encodeUuid ($value))->first();
 }
```

This overwritten method could be included in the `HasBinaryUuid` trait quite easily. Not tested the above yet but I figured I'd share my thoughts.

**Comment by brendt** [comment]
@slashequip If you're up for it, feel free to send a PR, we might indeed merge this instead of overriding `getRouteKeyName`.

There's also talk to add binary UUIDs and binding support in Laravel itself, though it's nowhere near concrete yet. That would of course be the best solution.

**Comment by slashequip** [comment]
@brendt I'll see if I can find some time this week to test my initial thoughts and I'll ping you a PR.

**Comment by brendt** [comment]
#36 was merged and tagged: https://github.com/spatie/laravel-binary-uuid/releases/tag/1.1.5
