### ISSUE TITLE
Accessors for non-primary-key UUID fields

### ISSUE THREAD

**Issue by westphalen** [spatie/laravel-binary-uuid#33]
The `HasBinaryUuid` trait seems to forcefully convert the primary key to its text representation during `toArray`. Even if this was the wanted behavior, any other UUID fields are left on their own. For example, a "belongs to" scenario, where a `user_id` or `user_uuid` binary UUID exists, nothing is done to convert that field to text. That leads to unclear exceptions due to `json_decode` failing for the binary field.

For consistency, the primary key should probably not forcefully be converted to text. Instead we could add something like `public $uuidFields = ['id', 'user_id'];` to the models. A default value for `$uuidFields` could take care of the automatic conversion of the primary key, while the user may set `$uuidFields = []` to disable that behavior.

**Comment by brendt** [comment]
Let's further discuss this in PR #35 👍

**Comment by choma** [comment]
I guess this should be reopened since the PR was abandoned, and this would be a nice feature

**Comment by brendt** [comment]
No need, the PR is still open, and I will look further into it when there's time. Unfortunately, I don't think I'll be able to give it attention anytime soon, so if you're up for it: feel free to fork the existing PR and submit it new one.
