### ISSUE TITLE
`HasUuidPrimaryKey` trait is redundant

### ISSUE THREAD

**Issue by westphalen** [spatie/laravel-binary-uuid#34]
The `HasBinaryUuid` trait already assumes that the primary key of the model should be a binary UUID:

```php
protected static function bootHasBinaryUuid()
{
    static::creating(function (Model $model) {
        if ($model->{$model->getKeyName()}) {
            return;
        }

        $model->{$model->getKeyName()} = static::encodeUuid(Uuid::uuid1());
    });
}
```

and also more or less expects the primary key name to be `uuid` (rather than `id` or whatever).

```php
public function getUuidTextAttribute(): string
```
```php
public function setUuidTextAttribute(string $uuid)
```

So `HasUuidPrimaryKey` trait doesn't influence whether the primary key will be treated as UUID, which is kind of bad, if you just want to use `HasBinaryUuid` trait for other attributes.
But even if the intention of `HasUuidPrimaryKey` is just an overkill way to change the primary key name from `id` to `uuid`, it makes no sense tha `HasUuidPrimaryKey` implements
```php
public function getIncrementing()
{
    return false;
}
```
while `HasBinaryUuid` doesn't.

The best behavior would be for `HasBinaryUuid` to leave the primary key alone, unless `HasUuidPrimaryKey` is set.

**Comment by brendt** [comment]
We're open for a PR to change this 😊

**Comment by slashequip** [comment]
@brendt I guess this can be closed now as `HasUuidPrimaryKey` is deprecated?

**Comment by brendt** [comment]
Indeed, as of 1.1.5, `HasPrimaryUuid` is deprecated and will be removed in 2.0.

More information about it in this PR: https://github.com/spatie/laravel-binary-uuid/pull/36
