### ISSUE TITLE
Not compatible with Scout

### ISSUE THREAD

**Issue by Wijnands** [spatie/laravel-binary-uuid#38]
On laraval 5.6 in combination with Scout I get a json utf 8 error

Imported [App\Models\Users] models up to ID: ���^�҆�����
and 
ERROR: JSON parsing error: malformed UTF-8 characters, possibly incorrectly encoded 

If i uninstall the packages and use uuid  as a string then the combination with scout is not a problem.

How can i fix the malformed utf-8 error?

**Comment by brendt** [comment]
If the binary UUID is used when serialising a model to JSON, this will result in an error. This package provides a built-in solution for queues, but it hasn't been tested with Scout. It is most likely possible to fix this for your models by overwriting the `toSearchableArray` in your model, and make sure the textual version of the UUID is returned and not the binary version. Without concrete error logs I cannot be sure that's the problem though.

There were some issues in this repo addressing the encoding, so I already wrote about it a lot in the past. If you're looking for how people solved those cases, here are a few examples:

- https://github.com/spatie/laravel-binary-uuid/issues/13
- https://github.com/spatie/laravel-binary-uuid/issues/30
