### ISSUE TITLE
Expose method to generate binary UUID

### ISSUE THREAD

**Issue by dror3go** [spatie/laravel-binary-uuid#42]
Hi,

I have a use case where I need to insert lots of rows to a table. To do so, my approach is to use Eloquent's `insert` method and provide it an array of data to insert, instead of creating lots of instances of my model and then `save()` each - which will run a single query per row. The goal is to optimize my INSERT process, since I require lots of data to be inserted to the table.
Since my table uses binary UUID as IDs, I need to include a binary ID in my array which I pass to the `insert` method. To do this, I used:
```MyModel::encodeUuid(\Ramsey\Uuid\Uuid::uuid1())```

It would be nice if the package provide a way to generate binary UUIDs.
Else - any suggestions for an alternative approach for INSERTing lots of rows?

Thanks a lot

**Comment by brendt** [comment]
Hi @dror3go 

If I understand correctly, you want a shorthand method for `MyModel::encodeUuid(\Ramsey\Uuid\Uuid::uuid1())`, maybe model agnostic?

That's indeed a convenient method. I'm not going to add this feature now, but will revisit it when we start working on a new major version. 

You're free to submit a PR if you want this in, but I'm not sure yet where the method would belong. Maybe a new class, or maybe on the `HasBinaryUuid` trait. 

Anyway, I'm closing the issue for now. We'll revisit it in a new version, or if you submit a PR.
