### ISSUE TITLE
Using Eloquent find* methods with string UUID

### ISSUE THREAD

**Issue by vpratfr** [spatie/laravel-binary-uuid#44]
Hi,

Currently we can only use the `find*` methods (find, findOrFail, etc) with binary UUIDs.

It would be nice to get those methods to work when given a valid UUID string too.

Would you be ok for a PR which would override those find methods in the trait to make use of the withUuid scode instead of the withKey scope when a UUID string is detected?

**Comment by vpratfr** [comment]
Here is some code that works, that I could submit in a PR with some tests if you agree:

```

    public static function find($id, $columns = ['*'])
    {
        if (\is_array($id) || $id instanceof Arrayable) {
            return static::findMany($id, $columns);
        }

        return static::withUuid($id)->first($columns);
    }

    public static function findMany($ids, $columns = ['*'])
    {
        if (empty($ids)) {
            return static::newModelInstance()->newCollection();
        }

        return static::withUuid($ids)->get($columns);
    }
```

**Comment by brendt** [comment]
Overriding `find` methods goes a bridge too far, as it touches too deep into default Laravel behaviour. I'd be ok with some custom scopes.

**Comment by vpratfr** [comment]
Ok. However that felt much more coherent with the rest of the features which allow to work seamlessly with string or binary representations.

And `MyModel::find($myUuidString)` is way more pleasant to write than the corresponding scoped query.

**Comment by yaquawa** [comment]
Agree with @vpratfr 🤝
This package already hacked in some internal behaviors that Laravel has. 

I know it's better not to touch the original method, but for the `find` method, just a little tweak can improve usability a lot and more importantly, can provide better integration ability with other packages which use the `find` method. And even if the original business logic of the `find` changes, it's just an easy catch up after all :)

@brendt  Please consider having the `find` accept string UUID 😿

**Comment by brendt** [comment]
@yaquawa we probably will: https://github.com/spatie/laravel-binary-uuid/pull/53 

Though I won't be able to merge it before September.

**Comment by yaquawa** [comment]
@brendt Thanks!😻

**Comment by vpratfr** [comment]
Closing this. Should be good now.
