### ISSUE TITLE
Make models with HasBinaryUuid trait serializable when the model key is not selected

### ISSUE THREAD

**Issue by d1am0nd** [spatie/laravel-binary-uuid#47]
Right now [this](https://github.com/spatie/laravel-binary-uuid/blob/master/src/HasBinaryUuid.php#L74) injects the key to the returned array, even when the key is not selected. Which makes `Model::select(fields)` a pain to use when the primary key is not selected.

Problem:
```php
// Model with `HasBinaryUuid` trait
Model::select('created_at')->first()->toArray();
```
Throws an error saying `uuid` cannot be `null`:

> TypeError: Argument 1 passed to Model::decodeUuid() must be of the type string, null given, called in spatie/laravel-binary-uuid/src/HasBinaryUuid.php on line 89

**Comment by brendt** [comment]
This is fixed, thanks to your PR; in 1.1.7: https://github.com/spatie/laravel-binary-uuid/releases/tag/1.1.7
