### ISSUE TITLE
Incorrect string value error when inserting into table

### ISSUE THREAD

**Issue by ramsey** [spatie/laravel-binary-uuid#5]
I created a table in MySQL 5.7 using the following migration class:

``` php
class CreateGroupsTable extends Migration
{
    public function up()
    {
        Schema::create('groups', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('name', 50);
            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::dropIfExists('groups');
    }
}
```

For MySQL, Laravel creates an `id` column of type `CHAR(36)` set as the primary key.

Unfortunately, when attempting to save a model, I received an error:

```
>>> $group = new Group();
=> App\Group {#744}
>>> $group->name = 'PUG Foo';
=> "PUG Foo"
>>> $group->save();

Illuminate\Database\QueryException with message 'SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xE7\xCF\xEA\x06\xE2\x0B...' for column 'id' at row 1 (SQL: insert into `groups` (`name`, `id`, `updated_at`, `created_at`) values (PUG Foo, ����
                                                    ��<���v, 2017-11-23 01:02:50, 2017-11-23 01:02:50))'
```

I tried several Laravel column type definition variations, including `binary()`, which uses MySQL's `BLOB` type instead of `BINARY` or `VARBINARY` and generates this error when attempting to set it as a primary key:

```
$ php artisan migrate

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'id' used in key specification without a key length (SQL: alter table `groups` add primary key `groups_id_primary`(`id`))
```

I was finally able to successfully save the model and use spatie/laravel-binary-uuid only after using raw SQL to create the `id` column as a `BINARY(16)` column in MySQL, like this:

``` php
class CreateGroupsTable extends Migration
{
    public function up()
    {
        Schema::create('groups', function (Blueprint $table) {
            $table->string('name', 50);
            $table->timestamps();
        });

        DB::statement('ALTER TABLE `groups` ADD COLUMN `id` BINARY(16) NOT NULL PRIMARY KEY FIRST');
    }

    public function down()
    {
        Schema::dropIfExists('groups');
    }
}
```

Now, my models save properly with binary UUIDs as primary keys.

I don't think there's anything to change in spatie/laravel-binary-uuid to fix this, but maybe the documentation should be updated.

Perhaps adding `binary` and `varbinary` types to `Illuminate\Database\Schema\Blueprint` in laravel/framework would help make this easier to use. Should I recommend this directly on laravel/framework? It appears it's been rejected in the past (https://github.com/laravel/framework/issues/3297), but it seems MySQL deals with binary data differently in `CHAR`/`VARCHAR` fields from`BINARY`/`VARBINARY` fields.

**Comment by ramsey** [comment]
I found a work-around that does the job without having to write raw SQL. Setting the `charset()` to "binary" on a `CHAR(16)` column effectively forces MySQL to create the column as `BINARY(16)`.

``` php
$table->char('id', 16)->charset('binary')->primary();
```

I'm assuming this might also work with the `uuid()` Blueprint type but that may end up creating a `BINARY(36)` column, which might not be preferable.

**Comment by brendt** [comment]
Hi Ben

One of the things this package does, is override the `uuid` grammar for MySQL and SQLite. When using `$table->uuid()`, it should automatically use `BINARY` as its column type instead of `BLOB`:

- https://github.com/spatie/laravel-binary-uuid/blob/master/src/MySqlGrammar.php
- https://github.com/spatie/laravel-binary-uuid/blob/master/src/SQLiteGrammar.php

Are you saying this didn't happen for your test project with the package enabled and the service provider registered?

**Comment by ramsey** [comment]
This did not happen for my project, but maybe I missed a step in setting it up. How do you register the service provider? I have a feeling that's the step I missed.

**Comment by ramsey** [comment]
Once I added `Spatie\BinaryUuid\UuidServiceProvider::class` to the providers array in `config/app.php`,  `$table->uuid('id')` worked as expected, creating a `BINARY(16)` column, so I'm closing this issue. Thanks!

**Comment by brendt** [comment]
Hi Ben

There was a day or so during development in which the auto registration of the service provider was broken, it's my guess that you required this repo during that time :)

**Comment by ramsey** [comment]
That could be. I also upgraded Laravel from 5.4 to 5.5 because I couldn’t install this package, so I may have installed it before adding one of the new scripts to `composer.json` that help support auto registration.
