### ISSUE TITLE
Is it necessary to explicitly set incrementing to false...?

### ISSUE THREAD

**Issue by telkins** [spatie/laravel-binary-uuid#50]
The docs suggest that "[t]o get your model to work with the encoded UUID (i.e. to use uuid as a primary key), you must let your model use the `Spatie\BinaryUuid\HasBinaryUuid`" but "[i]f [you] don't like the primary key named `uuid` you can leave off the `HasUuidPrimaryKey` trait and manually specify `$primaryKey`. **Don't forget set `$incrementing` to false.**"

However, `Spatie\BinaryUuid\HasBinaryUuid` has the following method:
```
    public function getIncrementing()
    {
        return false;
    }
```

So...shouldn't it be enough to just use `Spatie\BinaryUuid\HasBinaryUuid` and not explicitly set `$incrementing` to false...?

**Comment by isocroft** [comment]
Yeah it is... Sorry about the mix up with respect to the dos

**Comment by brendt** [comment]
@isocroft feel free to also improve this in your README PR 👍
