### ISSUE TITLE
Validation not working?

### ISSUE THREAD

**Issue by mfauveau** [spatie/laravel-binary-uuid#52]
Laravel 5.6
Laravel Binary Uuid 1.1

I'm sure I'm missing something here (I've been back to Laravel for only the past 6 months).

I have a model that uses the HasBinaryUuid trait. In my Request class, I want to check for uniqueness of one of the attributes, so I did:
```
    public function rules()
    {
        return [
            'name'                      => [
                'required',
                'max:255',
                'unique:model_table,name,'.$this->model_name->id
            ],
```

Unfortunately, the following error occurs:
```
[2018-08-10 15:49:01] local.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`?' at line 1 (SQL: select count(*) as aggregate from `model_table` where `name` = Test and `�\';L�` <> 蜱��)
```

Any ideas?

**Comment by isocroft** [comment]
@mfauveau when you read the `->id` or `->uuid` attribute of any model that uses the **HasBinaryUuid** trait, it returns binary data. The error you have has nothing to do with this package. From the error, you are trying to query with a binary column (which is impossible). First you need to specify the actual column and then the value (which is the binary `id`)

I think what you wished to do is:

```php

use Illuminate\Validation\Rule;

public function rules()
    {
        return [
               'name' =>[
                      'required',
                      'max:255',
                       Rule::unique('model_table', 'name')->where(function ($query) {
                               return $query->where(
                                              $this->model_name->getKeyName(), 
                                              '<>', 
                                              $this->model_name->id
                                      );
                     })
                  ]
           ]
   }
```

OR 

```php

   public function rules()
    {
        return [
            'name'  => [
                'required',
                'max:255',
                'unique:model_table, name, id, ' . $this->model_name->id
            ]
  }

```
.

**Comment by brendt** [comment]
Looks like it's indeed a misuse of certain properties. I'll close this issue for now, but don't hesitate to reply here if you have any more questions.

**Comment by mfauveau** [comment]
For some reason, id_text was throwing an error and it's not doing it anymore... thanks anyway, guys!

**Comment by mfauveau** [comment]
I actually remember now (I have a case of Mondays :)).

When editing an item, let's say ```22509e3c-9a74-11e8-99a9-0800273b4cc5```, neither ```Rule::unique('table')->ignore($this->model->id_text)``` or ```Rule::unique('table')->ignore($this->model->id)``` work as expected. It's always returning "name" attribute already exists.

I found out that dumping $this->model->id returns ```b"\x11èšt"Pž<™©\x08\x00';LÅ"``` but dumping $this->model->id_text returns ```null```.

Not sure why I can't get this simple validation working. 

To give more context, this is all contained in ```Request::rules()```, and automatically called from the ```Controller::update(Request $request, Model $model)``` method.

Also the model already contains
```
   public function getKeyName()
    {
        return 'id';
    }
```
as well as
```
    protected $uuids = [
        'id'
    ];
```

**Comment by mfauveau** [comment]
Ok, ```$this->id```returns the actual text uuid. Progress! However, I've attempted all of the proposed solutions, and I still get the "name" attribute already exists error.

**Comment by brendt** [comment]
Reopening this, I'll investigate it a little further, though I can't promise it'll be this week.

**Comment by isocroft** [comment]
@mfauveau does your model contain ?

```php

public function getRouteKeyName(){

       return 'id_text';
}
```
if it doesn't then what you are looking for is on `$this->model->uuid_text`. I think there would be need to update these two methods in the library code @brendt like so (just a suggestion):

```php
    public function getKeyName(){

               return $this->primaryKey;
    }

    public function getRouteKeyName(){
           
            $id = $this->getKeyName();
            $suffix = $this->getUuidSuffix();

            return "{$id}{$suffix}";
     }
```

So, it's easier to use the library without wondering about so much like @mfauveau .

**Comment by alexqhj** [comment]
Any update on this? I'm having trouble finding an elegant solution to validation through form requests that doesn't involve `all()` or similar drastic methods.

I'm looking to validate that a uuid exists in a table. Html doesn't allow the binary version of the uuid so I'll have to convert it.

Edit:
After some more work I found a "sort of elegant" solution.

**In the form request**

    protected function prepareForValidation()
    {
        $this->merge(['foo'=> Foo::encodeUuid($this->foo)]);
    }

Though this doesn't persist the change. Back in your controller you'd still need to `encodeUuid` again to insert it into the database (at least for pivots/relations)

**Comment by freekmurze** [comment]
This package has been abandoned. Alternatives: https://github.com/michaeldyrynda/laravel-efficient-uuid & https://github.com/michaeldyrynda/laravel-model-uuid
