### ISSUE TITLE
Unknown database type binary requested, Doctrine\DBAL\Platforms\SqlitePlatform may not support it.

### ISSUE THREAD

**Issue by fincardy** [spatie/laravel-binary-uuid#57]
Hey there,

I'm using this alongside Laravel Dusk with SQLite for testing purposes, problem is when I try and run the db migrations I get this error:

`Doctrine\DBAL\DBALException: Unknown database type binary requested, Doctrine\DBAL\Platforms\SqlitePlatform may not support it.`

I've not really used Dusk or SQLite before and after some digging SQLite doesn't have the "binary" datatype but instead uses "blob".

I checked the SQLiteGrammar file and it specifies `binary(16)` for the `typeUuid` - changing this to `blob(256)` fixes the issue.

Just wondering if it's something I'm doing wrong or should the Grammar file specify the `blob` data type?

thanks

**Comment by brendt** [comment]
Yeah, that's probably a bug. Feel free to submit a PR!

**Comment by fincardy** [comment]
Thanks for the quick reply, submitted the PR now :)

**Comment by brendt** [comment]
It's merged! #58
