### ISSUE TITLE
Can't store values in a model with UUID in it

### ISSUE THREAD

**Issue by rohanshukla94** [spatie/laravel-binary-uuid#62]
So I set it up everything perfectly but when I create a 'store' function it says this

``SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value (SQL: insert into `users` (`name`, `email`, `password`, `uuid`, `updated_at`, `created_at`) values\

Do i also need to specificy the uuid inside the add function? Doesn't it get generated automatically like 'id' use to?

**Comment by rohanshukla94** [comment]
It's done, I solved it! Thanks.

**Comment by brendt** [comment]
@NietzscheCoder could you share the problem and solution for future reference?

**Comment by rohanshukla94** [comment]
Yes, wait ill do that

**Comment by rohanshukla94** [comment]
@brendt this wasn't an error from the package side, it was rather a mistake in the code i was using for Create function, other than that this error wouldn't come.
