### ISSUE TITLE
[Idea] Split up HasBinaryUUID trait

### ISSUE THREAD

**Issue by afraca** [spatie/laravel-binary-uuid#64]
The `HasBinaryUUID` trait is quite 'all in'. It's not so easy to mix how your models work. 

If your model A does not have binary uuid, but B has, and you're working with relations, it's nice to have the toArray() from the trait, but I don't want the creating listener code.

**Comment by brendt** [comment]
There actually were multiple traits in a previous version. We decided to go all in for a better default user experience. For some people this is a good thing, for other it's not. 

Furthermore, this would mean a breaking change. I'll tag this issue so that we'll revisit it for a next major version.

**Comment by vpratfr** [comment]
Note for later. A non breaking way to do that would be to split it in several traits and then the existing trait would use all those smaller pieces.
