### ISSUE TITLE
Composite Key Not Working

### ISSUE THREAD

**Issue by XanManZA** [spatie/laravel-binary-uuid#66]
Just basically doing a sanity check here because I'm assuming the changes were tested.
In the README it states that composite keys are supported, thus steps:

1. Create a model and make it extend `Illuminate\Database\Eloquent\Relations\Pivot`
2. Add `use Spatie\BinaryUuid\HasBinaryUuid;`
3. Change the `getKeyName` method, as stated in README
```
public function getKeyName()
{
    return ['key_id', 'key_id_two'];
}
```
4. Try to create Model with tinker and receive 
> PHP Notice:  Array to string conversion in vendor/spatie/laravel-binary-uuid/src/HasBinaryUuid.php on line 14

**Comment by brendt** [comment]
That looks like an oversight in the package.

I believe @isocroft made the initial change. Ifeora , Do you have input on how to fix this the best way?

**Comment by XanManZA** [comment]
Cool, just to confirm that the problem is the fact that a pivot typically does not need to generate a primary key. So the `creating` boot watcher should either not happen in that case or the logic inside it should change.
Let me know if you'd rather have me create a PR.

**Comment by brendt** [comment]
@XanManZA a PR is definitely welcome!

**Comment by XanManZA** [comment]
> @XanManZA a PR is definitely welcome!

Cool, will get to it this weekend

**Comment by isocroft** [comment]
Yeah @brendt , it was actually an oversight. Thanks so much @XanManZA  for pointing this out. 

Here is the ( quick ) code that would be fixing it in *HasBinaryUuid.php*.

```php

   /* newly defined method */

   public function getUuidKeys()
   {

        return (property_exists($this, 'uuids') 
                             && is_array($this->uuids)) ? $this->uuids : [];
   }

   /* modified method */

   public function getUuidAttributes()
    {
        $uuidKeys = $this->getUuidKeys();
        
        // non composite primary keys will return a string so casting required
        $key = (array) $this->getKeyName();

        $uuidAttributes = array_unique(array_merge($uuidKeys, $key));

        return $uuidAttributes;
    }

    /* modified static method */

        protected static function bootHasBinaryUuid()
    {
        static::creating(function (Model $model) {
            $keyName = (array) $model->getKeyName();
            $uuidAtrributes = $model->getUuidKeys(); 

           /* if(is_string($keyName)){
                 $keyName = [ $keyName ];
            }*/

            foreach($keyName as $key){
                 if (!in_array($key, $uuidAtrributes)
                       || $model->{$key}) {
                      return;
                 }
                 $model->{$key} = static::encodeUuid(static::generateUuid());
            }
            
        });
    }

  
```

@XanManZA I hope this helps with your proposed PR.

**Comment by vpratfr** [comment]
What if the composite key is not made of 2 UUIDs? 

For instance an uuid and an id or a string.

I guess you should check against the `$uuids` property to see if the key is declared as a uuid.

**Comment by isocroft** [comment]
Thanks for that angle @vpratfr . Have updated the code above to take those into consideration

**Comment by XanManZA** [comment]
@brendt I don't want to mess up your cheese here, what would be your expected behaviour on the `setUuidTextAttribute` for composite keys?
 The solution @isocroft offered will set all the keys to the same UUID if I understand correctly, which is not good I think.
So either we force the attribute parameter to be an array or put a disclaimer in the ReadMe that the `uuid_text` attribute is not applicable to composite keys

**Comment by brendt** [comment]
At Spatie, we don't need the composite keys at the moment. So it's up to the people actually benefiting from this feature to raise their voice: yes or no. 

My personal preference goes to simply change the README. If we ever choose to build this package from the ground up (v2) we might reconsider it. But feel free to change my mind on why this feature is a must and why it should be supported.

**Comment by isocroft** [comment]
@XanManZA i think we should put the disclaimer in the ReadMe. The `setUuidTextAttribute()` method is only applicable to the primary key column for the current Eloquent model. I think this approach is best. 

Any other suggestions are welcome...

**Comment by vpratfr** [comment]
How about throwing an exception if that method is called inside a model with a composite key? Would make it obvious then.

**Comment by brendt** [comment]
@vpratfr I like that idea!

So, is anyone up for sending a PR? Otherwise I'll look at it when I've got the time. (Which won't be this week.)

**Comment by isocroft** [comment]
@vpratfr love your idea! It follows proper flow for this case. Let me send in a PR later on Friday this week so we all can discuss some more.

**Comment by isocroft** [comment]
For PR #71 which i pushed recently all tests are passing except 1 (the test for composite keys) which makes use a new model that defines composite keys. The test passes on my local but **Travis CI** reports an error:

`class "Spatie\BinaryUuid\Test\TestModelComposite" not found`

@brendt  how do i fix please so the PR can go through for further discussions ?

**Comment by brendt** [comment]
@isocroft I guess there's either a typo somewhere or a wrong namespace mapping. Both are fixed locally by running `composer dump-autoload`, which can hide the problem.

**Comment by isocroft** [comment]
Thanks a lot @brendt fixed it. turns out the file somehow wasn't commited when i pushed

**Comment by isocroft** [comment]
Going forward,

I think this piece of code from https://github.com/coenjacobs/eloquent-composite-primary-keys/ should be considered for inclusion into the **HasBinaryUuid** trait as well. Besides the composite primary keys library i referenced above is actually too small to be a stand-alone composer library

```php
    /**
     * Set the keys for a save update query.
     *
     * @param  Builder $query
     *
     * @return Builder
     * @throws Exception
     */
    protected function setKeysForSaveQuery(Builder $query)
    {
        foreach ($this->getKeyName() as $key) {
            if ( ! isset($this->$key)) {
                throw new Exception(__METHOD__ . 'Missing part of the primary key: ' . $key);
            }
            $query->where($key, '=', $this->$key);
        }
        return $query;
   }
```

What do you all think ?

**Comment by freekmurze** [comment]
This package has been abandoned. Alternatives: https://github.com/michaeldyrynda/laravel-efficient-uuid & https://github.com/michaeldyrynda/laravel-model-uuid
