### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by andreidmour** [spatie/laravel-binary-uuid#69]
Using Passport and User UUID causes "Malformed UTF-8 characters, possibly incorrectly encoded" in oauth/token

**Comment by vpratfr** [comment]
Can you paste your model class here?

**Comment by nolanpro** [comment]
I get this too. There's an issue when outputting a JSON stack trace that includes the SQL (maybe other places too). I don't have a viable workaround so I hope someone can help out.

I can fix the issue by modifying `vendor/laravel/framework/src/Illuminate/Database/QueryException.php`

```
$this->message = $this->formatMessage($sql, $bindings, $previous);
```
to
```
$this->message = utf8_encode($this->formatMessage($sql, $bindings, $previous));
```

But of course we shouldn't modify vendor files directly. I'm trying to figure out how to use macros or facades to achieve the same thing. Any ideas?

**Comment by yaquawa** [comment]
Checkout #61

**Comment by freekmurze** [comment]
This package has been abandoned. Alternatives: https://github.com/michaeldyrynda/laravel-efficient-uuid & https://github.com/michaeldyrynda/laravel-model-uuid
