### ISSUE TITLE
Ordered UUID for Laravel MySQL grammar query compilation via custom builder

### ISSUE THREAD

**Issue by isocroft** [spatie/laravel-binary-uuid#74]
Once pending PRs are reviewed/attended to, it will be pertinent to consider ordered uuids for setting up partial sequential ids in database tables making it easy to sort/index at DB level. The custom eloquent builder and grammar PHP classes in this package will be updated to have this new behaviour. This could be the basis of a version 2 of the package focusing on performance with respect to UUIDs.

For context, see:

https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way

**Comment by freekmurze** [comment]
This package has been abandoned. Alternatives: https://github.com/michaeldyrynda/laravel-efficient-uuid & https://github.com/michaeldyrynda/laravel-model-uuid
