### ISSUE TITLE
Running DB::purge() is unloading extension

### ISSUE THREAD

**Issue by guice** [spatie/laravel-binary-uuid#76]
Using a DB::purge() to reset the database connection is unloading this UUID plugin, causing an issue with multi-database sites.
---
I'm using a multi-database approach on our website. I'm building a multi-db migration using [a method of overloading the migration commands](https://hackernoon.com/extending-laravels-migration-command-to-add-new-options-90b5a0fc4ef4
) I found online. 

However, I discovered an issue when attempting to use this extension in combination with the `DB::purge()` method for re-initializing the DB resources for the second database. When I use `DB::purge()` this extension seems to get unloaded. When I try to use `DB::disconnect()` I run into migration issues, due to latent knowledge of `migration` table.

Is there anyway to re-instantiate this plugin when I need to purge out existing db connections?

**Comment by brendt** [comment]
That's a very strange issue. Is there any chance you'll be able to figure out why the package gets unloaded?

Also, what kind of errors do you get? Are you sure the package isn't registered anymore?

**Comment by guice** [comment]
Here's what I'm seeing:

* I have a migration I'm overloading: `migrate:refresh --seed`
* I set my migration directory for my first default, run ::handle()
* Then I look over a series of clients, each doing:
```php 
    protected function setDatabase(string $db_name)
    {
        config(['database.connections.default.database' => $db_name]);
        \DB::purge();
    }
```
* Outcome:
  * The first db has binary(16) as UUID columns
  * All subsequent client DBs have UUID columns as char(36)

I ran through a debug, and I can definitely see in the first ::handle() call goes through the binary-uuid libraries to set UUID type. But in the client calls, after ::purge() it does not.

If I remove ::purge(), it works but all client tables are created in the base database. If I use ::disconnect() I get another error (migration table not found). So, I have to use `::purge()`

Here's my overload ::handle(): 
```php
    public function handle()
    {
        $this->getDefinition()->getOption("path")->setDefault('database/migrations/base/');
        parent::handle();

        $this->getDefinition()->getOption("path")->setDefault('database/migrations/client/');
        $this->getDefinition()->getOption("seeder")->setDefault('ClientDatabaseSeeder');

        $clients = [];
        if ($client = $this->option('client')) {
            $clients[] = $this->retrieveClient($client);
        } else {
            $clients = $this->getClients(); // Gets a list of clients and their database name.
        }

        foreach ($clients as $client) {
            $this->insureSchema($client->db_name); // Runs CREATE DATABASE IF NOT EXISTS
            $this->setDatabase($client->db_name); // Runs the above, with `::purge()`
            parent::handle();

            $this->call('passport:install');
        }
    }
```

**Comment by brendt** [comment]
My best guess is to look at the service provider of this package: https://github.com/spatie/laravel-binary-uuid/blob/master/src/UuidServiceProvider.php maybe you'll be able to figure things out from there?

I'll be closing this issue as there's no specific support in this package with multiple databases. But feel free to keep commenting.
