### ISSUE TITLE
uuid() blueprint method creates a char(36) column instead of binary(16)

### ISSUE THREAD

**Issue by jonagoldman** [spatie/laravel-binary-uuid#77]
I am using v1.3.0 of this package with Laravel v5.6.39.

According to the docs, `$table->uuid('uuid')`  is supposed to create a `binary(16)` column in database, but for some reason a `char(36)` is created instead.

I am changing database connections on the fly, so maybe that's the problem? Maybe the override behavior of Laravel's uuid() method is not working or something is not registering correctly?

**Comment by brendt** [comment]
It sounds like the service isn't loaded correctly. Our service provider will register the custom grammar on boot: https://github.com/spatie/laravel-binary-uuid/blob/master/src/UuidServiceProvider.php

My guess is that by changing the connection on the fly, you'll also have to manually override the grammar for that connection.

Unfortunately this package doesn't explicitly support this feature, so I'll be closing the issue. If you find a solution for the problem though, you're free to send a PR.
