### ISSUE TITLE
Use OrderedTimeCodec from ramsey/uuid

### ISSUE THREAD

**Issue by barryvdh** [spatie/laravel-binary-uuid#8]
The re-ordered encoding is also supported by ramsey/uuid, see https://github.com/ramsey/uuid/blob/master/src/Codec/OrderedTimeCodec.php

Perhaps it's easier to use that instead?

See for background https://github.com/ramsey/uuid/pull/118

**Comment by freekmurze** [comment]
Thanks for letting us know. This has been taken care of in `v1.0.1`.
