### ISSUE TITLE
Question - Should I still have a fk defined $casts?

### ISSUE THREAD

**Issue by louisl** [spatie/laravel-binary-uuid#81]
I'm converting a schema to use uuids.

In my model I have
```php
    /**
     * Casts
     *
     * @var array
     */
    protected $casts = [
        'country_id' => 'int',
    ];
```

I see in the readme that I should add
```php
    /**
     * The binary UUID attributes that should be converted to text.
     *
     * @var array
     */
    protected $uuids = [
        'country_uuid' // foreign or related key
    ];
```
So I'm removing the column `country_id` and replacing it with `country_uuid`.

The question is, do I need to define that in any way in `$casts` or is that replaced for uuids by the `$uuids` array?

**Comment by vpratfr** [comment]
No need to have that in `$casts`. Just in `$uuids`

**Comment by louisl** [comment]
Thank you, maybe stick that in the readme for clarity.
