### ISSUE TITLE
General error: 1215 Cannot add foreign key constraint when using relations

### ISSUE THREAD

**Issue by basepack** [spatie/laravel-binary-uuid#83]
Hi,

I am getting this error when running:  `php artisan migrate:refresh --seed`. If I change back to normal ids I do not get this error.

Full error:
`
   Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `invoicerows` add constraint `invoicerows_invoice_id_foreign` foreign key (`invoice_id`) references `invoices` (`id`) on delete cascade)
`

My old migrations:

```php
// Invoices migration
Schema::create( 'invoices', function ( Blueprint $table ) {
	$table->increments( 'id' );
}
```

```php
// Invoicerows migration
Schema::create( 'invoicerows', function ( Blueprint $table ) {
	$table->increments( 'id' );

	$table->integer( 'invoice_id' )->unsigned()->nullable();
	$table->foreign( 'invoice_id' )->references( 'id' )->on( 'invoices' )->onDelete( 'cascade' );
}
```

New migration after installing `spatie/laravel-binary-uuid':
```php
// new Invoices migration
Schema::create( 'invoices', function ( Blueprint $table ) {
	$table->uuid('uuid');
        $table->primary('uuid');
}
```

```php
// New Invoicerows migration
Schema::create( 'invoicerows', function ( Blueprint $table ) {
	$table->uuid('uuid');
        $table->primary('uuid');

	$table->integer( 'invoice_uuid' )->unsigned()->nullable();
	$table->foreign( 'invoice_uuid' )->references( 'uuid' )->on( 'invoices' )->onDelete( 'cascade' );
}
```

When I now run `php artisan migrate:refresh --seed` I get that error. 

I have tried to add my original `id` field: `$table->increments( 'id' );` but I suppose you do not need an id field anymore when using binary uuids?

**Comment by vpratfr** [comment]
This is the culprit:

    $table->integer( 'invoice_uuid' )->unsigned()->nullable();

Should be

    $table->uuid( 'invoice_uuid' )->nullable();

**Comment by basepack** [comment]
@vpratfr, great catch! It was a long day I suppose :smile:
