### ISSUE TITLE
Relies on static UUID factory not being changed

### ISSUE THREAD

**Issue by uphlewis** [spatie/laravel-binary-uuid#84]
Currently the library sets the static default Uuid factory with OrderedTimeCodec at boot in the package service provider.

The issue is where somewhere else in the application changes the static factory and uses a different codec.

Solution is to register a singleton OrderedTimeCodec in the service container, and resolve the instance whenever it is needed.

Will submit a PR.

Thanks for the library :) Although it's not quite suitable for my needs, I was able to adapt some ideas for my own project.

**Comment by brendt** [comment]
Thanks! Feel free to submit a PR.

**Comment by uphlewis** [comment]
PR submitted: https://github.com/spatie/laravel-binary-uuid/pull/85

**Comment by freekmurze** [comment]
We'll continue the conversation in #85
