### ISSUE TITLE
Lack of "ID" in key name results in exception

### ISSUE THREAD

**Issue by spencerwasden** [spatie/laravel-binary-uuid#86]
I'm using a legacy schema that won't be modified.  A uuid column named "CreatedBy" does not contain "id" or "uuid", so `getRelatedBinaryKeyName` doesn't return the attribute with suffix.  Commenting out the `preg_match` line and just returning `"{$attribute}{$suffix}"` fixes the issue:

```php
    public function getRelatedBinaryKeyName($attribute): string
    {
        $suffix = $this->getUuidSuffix();

      //return preg_match('/(?:uu)?id/i', $attribute) ? "{$attribute}{$suffix}" : $attribute;
        return "{$attribute}{$suffix}";
    }
```
Since the CreatedBy column is provided in the model's `$uuids` array, should `getRelatedBinaryKeyName` really be doing that check for "uuid" or "id"?  If so, could this be made to be conditional based on a config setting?

The exception is thrown from here in Illuminate/Http/JsonResponse.php:
```php
if (! $this->hasValidJson(json_last_error())) {
    throw new InvalidArgumentException(json_last_error_msg());
}
```
Exception:
`InvalidArgumentException.  Malformed UTF-8 characters, possibly incorrectly encoded`

**Comment by freekmurze** [comment]
This package has been abandoned. Alternatives: https://github.com/michaeldyrynda/laravel-efficient-uuid & https://github.com/michaeldyrynda/laravel-model-uuid
