### ISSUE TITLE
Can we have an incremental id (for internal relations) too?

### ISSUE THREAD

**Issue by AmirrezaNasiri** [spatie/laravel-binary-uuid#87]
The package handles UUID greatly but using UUID for everything doesn't make sense.

For example, we can use UUID as external key to requested resource and an incremental id to handle internal requests (and relations). But by disabling `$incrementing`, we're unable to have both.

So my question is how is it possible to have an incremental id alongside an optimized UUID and actually use them?

**Comment by brendt** [comment]
You can always add an auto incremented column for internal use, eg. for relations.
