### ISSUE TITLE
Conflict with Laravel Telescope

### ISSUE THREAD

**Issue by thannaske** [spatie/laravel-binary-uuid#89]
There is a problem using this package together with Laravel Telescope as it's overwriting the Blueprint's UUID method. When using this package Laravel Telescope does not work anymore.

(see: https://github.com/laravel/telescope/issues/332)

**Comment by brendt** [comment]
If we ever get around making a v2, this problem will be solved. But there's no plans to do that in the immediate future. If the community wants to help, they're welcome to do so.
