### ISSUE TITLE
Looking for maintainers / abandonment notice

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-binary-uuid#91]
Because we don't use this package ourselves anymore we can't justify the work maintaining this package anymore.

If somebody that uses this package heavily and has made previous contributions wants to step up as a maintainer, let me know at freek@spatie.be

If nobody is up for it, we'll abandon this package in a few weeks.

If you have a package that serves as an alternative to this one, let me know and I'll put a link to your package in our readme.

**Comment by kjfdebruin** [comment]
Hey @freekmurze - thanks for all the amazing work that you do. I discovered this package today, and it looks like the best one available.

Would you mind posting here which package you replaced this one with internally?

**Comment by freekmurze** [comment]
We'll just keep using this one in an old project. But we don't want to maintain the package anymore. There are no new projects where we're planning to use this package.

**Comment by fgilio** [comment]
There are also this 2 packages for working with UUIDs in Laravel: https://github.com/michaeldyrynda/laravel-efficient-uuid & https://github.com/michaeldyrynda/laravel-model-uuid

**Comment by freekmurze** [comment]
@fgilio thanks for the suggestions.
